supertokens vs express-session blog
supertokens/blog pull request #188
Opened 2023-09-20 07:18 UTC by Chakravarthy7102

# Related Issue
Link to the Github Issue created for this blog post

# Link to Google Doc
TODO

# Checklist
- [ ] Has cover image been added
- [ ] Have all content images been added. Do they render correctly? (aspect ratio etc)
- [ ] The code inside code blocks gives no errors
- [ ] Check for SEO keyword?
- [ ] Added call to action to link to supertokens and to link to other blogs.
- [ ] Add reference to how SuperTokens solves this blog's problem (if relevant).

# Remaining TODOs
- [ ] ...

2023-09-26 05:27 UTC, jscyo requested changes

2023-09-26 05:27 UTC, jscyo commented on content/express-session-vs-supertokens-for-handling-user-sessions/index.md
> +This article will be comparing SuperTokens to Node’s most popular [session management](https://www.packetlabs.net/posts/session-management/) library – express-session. The comparison will be done usi
```suggestion
This article will be comparing SuperTokens to Node’s most popular session management library – [express-session](https://www.npmjs.com/package/express-session). The comparison will be done using a point system, where a point will be awarded to a library’s score if it performs well in a given metric. Here are the metrics we will be using:
```

2023-10-05 06:26 UTC, nkshah2 approved these changes

2023-10-05 06:28 UTC, jscyo approved these changes
LGTM

2023-10-05 06:30 UTC, merged